### ISSUE TITLE
Field specific operators

### ISSUE THREAD

**Issue by hellofantastic** [Lefortov/react-two-way-querybuilder#1]
Hey great module.

I am trying this out and am trying to have specific operators per field but that seems to crash my app unless i only have it set as ... operators: 'all' ...

i have tried
```javascript
...
{name: 'name', label: 'Account Name', input: { type: 'text' },operators: [ { operator: '=', label: '=' },{ operator: '<>', label: '<>' }] } ,
...
```
AND as per read me
```javascript
...
{name: 'name', label: 'Account Name', input: { type: 'text' },operators: [  '=',  '<>'] } ,
...
```

**Comment by hellofantastic** [comment]
Hey @Lefortov here it is, an endless loop:

      for (let opIndex = 0, opLength = this.props.operators.length; opIndex < opLength; opLength += 1) {

'opLength += 1' needs to be changed to 'opIndex += 1'

**Comment by hellofantastic** [comment]
@Lefortov Thanks for the Pull approval and merge! This is sweet!

**Comment by Lefortov** [comment]
@hellofantastic Thank you for fixing this regrettable mistake.
