### ISSUE TITLE
Loading an existing query not working correctly

### ISSUE THREAD

**Issue by hellofantastic** [Lefortov/react-two-way-querybuilder#4]
Your demo for existing query seems to be correct but if you try and load an existing query that has select dropdown , or uses any operator other than '=' is gets messed up.
Example if i set a query like this: 
![screen shot 2017-05-12 at 4 35 14 pm](https://cloud.githubusercontent.com/assets/6655746/26020265/42df9498-3731-11e7-980a-119da0ad268e.png)
The query looks like this:

(name = ' Fred' AND offices IN 'Oakland')

But if I try and Load that query in 
```javascript 
config = { query: "(name = ' Fred' AND offices IN 'Oakland')" }
```
it builds the query UI messed up 

![screen shot 2017-05-12 at 4 34 52 pm](https://cloud.githubusercontent.com/assets/6655746/26020295/9b71ecb4-3731-11e7-96eb-51dab12ff35e.png)

Offices isn't selected and its operator is incorrect and the N from IN operator is added to value and value is cut off?Also noticed extra space it added...

Any insight?
Does that token creator function need some refactoring maybe

**Comment by Lefortov** [comment]
Thank you for detailed description, working on fix.

**Comment by Lefortov** [comment]
As a temporary solution it's needed to use lowercase operators `is null`, `is not null`, `in`, `not in` instead of `IS NULL`, `IS NOT NULL`, `IN`, `NOT IN`. Would be refactored a bit later
